sudo: required
services:
  - docker
before_install:
  - docker build -t tranthienbinh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tranthienbinh/docker-react npm run test

language: generic 